# Numpy Practice

Proceed with this challenge only if you feel comfortable with Monday's and Tuesday's assignments. If you feel you should spend this time reviewing the lecture/assignments, please do that instead.



---



## 1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

In [1]:
import numpy as np

l = [12.23, 13.32, 100, 36.32]
print("Original List:",l)

Original List: [12.23, 13.32, 100, 36.32]


In [2]:
a = np.array(l)
print("One-dimensional numpy array: ",a)

One-dimensional numpy array:  [ 12.23  13.32 100.    36.32]




---



## 2. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.



In [3]:
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]




---



## 3. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

In [4]:
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]




---



## 4. Write a NumPy program to create a array with values ranging from 12 to 38.

In [5]:
x = np.arange(12, 38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]




---



## 5. Write a NumPy program to reverse an array (first element becomes last).

In [6]:
x = np.arange(12, 38)
print("Original array:")
print(x)

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [7]:
print("Reverse array:")
x = x[::-1]
print(x)

Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]




---



## 6. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [8]:
x = np.ones((5,5))
print("Original array:")
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]




---



## 7. Write a NumPy program to find common values between two arrays.

In [10]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]


In [11]:
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Common values between two arrays:
[10 40]




---



## 8. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.

In [12]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]


In [13]:
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]




---



## 9. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

In [14]:
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)

Original array: 
[[ 0 10 20]
 [20 30 40]]


In [15]:
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))




---



## 10. Write a NumPy program to create a new shape to an array without changing its data.

In [16]:
x = np.array([1, 2, 3, 4, 5, 6])

In [17]:
y = np.reshape(x,(3,2))
print("Reshape 3x2:")
print(y)
z = np.reshape(x,(2,3))
print("Reshape 2x3:")
print(z)

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]




---



Congrats, now go review yesterday's material.